title: "Jon's Miscellany"
encoding: UTF-8
author: "Jon Gjengset"
email: pod@jonhoo.eu
subtitle: "A collection of Jon Gjengset's videos (https://www.youtube.com/@jonhoo) suitable for audio-only consumption."
description: "For now, this site primarily re-hosts the Q&A videos in audio format."
lang: en-us
kramdown:
  input: GFM
  hard_wrap: false
repository: jonhoo/pod-misc
url: https://pod.jonhoo.eu

exclude:
  - 000-template.md
  - vendor
  - audio
collections:
  episodes:
    output: true
    permalink: /episode/:title/
  transcripts:
    output: true
    permalink: /transcript/:title/

# https://github.com/jekyll/jekyll/issues/7744
defaults:
 - scope:
     path: ""
     type: "episodes"
   values:
     layout: "episode"
 - scope:
     path: ""
     type: "transcripts"
   values:
     layout: "transcript"
